- .github/workflows/nvda-chrome.yml
Move the checkouts above the `setup-node` action and configure it to use `**/package-lock.json` to detect the cache keys (might help slightly with install times *cross fingers*)
> Checkout all repos and npm cache based on combined package lock

- .github/workflows/nvda-test.yml
- run-tester.ps1
Fixes #6
Downloads the latest release zip from [bocoup/aria-at-automation-nvda-builds](https://github.com/bocoup/aria-at-automation-nvda-builds) releases.
> Download NVDA portable ZIP from external repo

- .github/workflows/nvda-chrome.yml
In implementing a new GitHub workflow for use in ARIA-AT App ("nvda-test.yml"), a recent commit [1] unintentionally regressed support for the existing GitHub Workflow ("nvda-chrome.yml").
Ensure that the "nvda-chrome.yml" workflow continues to operate as originally intended in order to facilitate an asynchronous transition to the new workflow.
[1] 715a21f0ad25c29518af9de1e7495b5bb2bf5875
---
@gnarf I was tempted to revert 715a21f0ad25c29518af9de1e7495b5bb2bf5875 in order to submit this as a new version of that patch which introduced the new feature atomically and completely. The reversion didn't apply cleanly, though, and resolving the conflicts seemed more complicated (not to mention risky) than warranted.
> Restore support for legacy workflow

- .github/workflows/nvda-test.yml
Noticed that there was a possibility of logging the ERROR status in the current app deploy so upgrading the new workflow to have a branch near the end to log ERROR instead of COMPLETED
> add callback to log the ERROR status for the error job

- .github/workflows/nvda-test.yml
I discovered an error that rarely happens on the [at-driver for NVDA](https://github.com/Prime-Access-Consulting/nvda-at-automation/issues/50) that causes the harness to hang indefinitely.  Adding a timeout to this step should hopefully stop us from spinning a GH Actions runner forever if this error happens again.
> Add timeout to harness run

- .github/workflows/nvda-test.yml
- .github/workflows/voiceover-test.yml
This PR adds support for specifying the AT version that a runner should use. 
- Thanks Corey for the matrix with an early exit suggestion!
- I opted for using conditionals in every action for the early exit so that that part of the matrix shows as completed rather than errored. It is verbose and I am open to alternatives if anyone has a suggestion.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1207376193363744
> Support runs with specific AtVersions

- .github/workflows/nvda-test.yml
This fixes a bug created by merging #21 before [aria-at-app/1144](https://github.com/w3c/aria-at-app/pull/1144) is merged. 
I made the mistake of thinking that the Github action that we are using to fetch releases of NVDA would fall back to the latest release. I also made the mistake of thinking that I had tested this behavior.
This PR adds fallback behavior so that when an `at_version` is not provided to an NVDA workflow, the latest is used.
> Hotfix:  Fallback to latest NVDA

- .github/workflows/voiceover-test.yml
Potential fix for https://github.com/w3c/aria-at-app/issues/1136
@stalgiag found that this was enabled by default for them in an update for macOS 14. This PR adds a configuration setting that disables this behavior.
The "Automatically Read Web Page" setting begins moving the keyboard before the test steps start, producing inaccurate results.
> add a setup step to turn off VO "Automatically Read Web Page" setting

- .github/workflows/voiceover-test.yml
Simplifies the voiceover-test.yml by removing the macos versions matrix and replacing it with the inputs.  This will result in one less worker being spawned for every test of voiceover (the unused mac os version).  This also then simplified the logic of the further tasks that were checking the result of a "should_run".
> remove job matrix for macos

- stressor/cancel-all-workflows.mts
- stressor/package.json
This is really helpful when you kick off a set of tests and then immediately realize you made a mistake and need to restart the process 😅
> Add a script to cancel all GitHub workflow runs in a repo

- .gitignore
- stressor/README.md
- stressor/package-lock.json
- stressor/package.json
- stressor/stress-test.mts
- removed checking for empty responses
- use a more markdown centric output format
- group output by test ids
- use a most common set of responses as the comparison set, instead of just using the first set of responses
> Update flakiness script

- stressor/package-lock.json
- stressor/package.json
"ts-node" and "tsx" are designed for the same use case, so the project needs only one of the two. Remove "ts-node" in favor of "tsx" due to the latter's more ergonomic command-line interface.
> Remove npm package "ts-node"

- stressor/package-lock.json
- stressor/package.json
- stressor/stress-test.mts
Require the leading "tests/" to reinforce the values' relationship to the ARIA-AT project repository.
(I think the "tests/" prefix requirement is useful friction (particularly because we lack a way to validate the existence of directories), but I won't fight if folks think it's gross.)
> Introduce a CLI option for test plans

- .pipelines/windows-nvda.yml
Unfortunately in my testing, the Azure DevOps REST API doesn't support setting "parameters", which are distinct from "variables". Furthermore, there are variables that are defined in the pipelines yaml file, but you can also define variables in the Azure Pipelines web UI. Variables defined in the YAML are not configurable outside of the YAML, aka you cannot set these programmatically when the build is triggered. Variables defined in the web UI can be configured to be settable at "queue time" which is when the build is triggered, either manually or via the REST API.
These UI variables have some kind of legacy status in Azure Pipelines, but they seem so to be the only way the REST API supports setting variables dynamically.
This PR reworks the azure pipeline file to rely on these queue time …
> Use queue time variables in azure pipeline

- .github/workflows/voiceover-test.yml
> disable MacOS notification center

- .github/workflows/nvda-test.yml
- .github/workflows/voiceover-test.yml
- run-tester.ps1
- run-tester.sh
Depends on https://github.com/w3c/aria-at-automation-harness/pull/75
> Use harness as published to NPM

- .github/workflows/nvda-test.yml
So we can send a PR upstream and be ready to swap this to the new "main" when it's landed.
Test run of job on branch: https://github.com/bocoup/aria-at-gh-actions-helper/actions/runs/13823173161/job/38672976069#step:4:62
> Pin nvda driver SHA

- stressor/stress-test.mts
Hey @gnarf, this seemed to minor to bug you about, but also a bit silly to do as a follow-up
> fixup! strip ansi color from diff output for markdown file

- stressor/lib/diff.mts
- stressor/stress-test.mts
- stressor/tsconfig.json
Small fix for the output of the diff - having the option to save it to a file now made the ansi colors break in the markdown
> strip ansi for diff output

- stressor/stress-test.mts
To align with the priority combinations tested by the ARIA-AT CG:
**Current Priority**
- NVDA + Chrome
- JAWS + Chrome
- VO + Safari
per @howard-e :
> When versions eventually get to RECOMMENDED, 3 additional combinations will be prioritized for them to be considered fully recommended:
> JAWS + Firefox
> NVDA + Firefox
> VO + Chrome
> removes firefox from testing matrix used in consistency reports

- .github/workflows/nvda-test.yml
- .github/workflows/voiceover-test.yml
Here is the version that pins to 0.0.3
✅  [Here](https://github.com/bocoup/aria-at-gh-actions-helper/actions/runs/14782671489/job/41504831864) is a voiceover test run 
✅  [Here](https://github.com/bocoup/aria-at-gh-actions-helper/actions/runs/14782666617/job/41504818817) is a NVDA test run
> pin automation-harness to 0.0.3

- .github/workflows/voiceover-test.yml
This also updates the default version of the macos-at-driver-server to the minimum version that's running the new AT-Driver `userIntent` updates. 
This does not update either the harness or AT-driver server versions for NVDA.
> Unpin harness version for Voiceover

- .github/workflows/nvda-test.yml
This is not yet complete, the draft only fixes for NVDA, we need to test and confirm "working" situation for voiceover yml as well.
We might want to set pinned version `0.0.4` for the aria-at-automation-harness so we don't accidentally an update like this again
[Here](https://github.com/gnarf/aria-at-gh-actions-helper/actions/runs/14781481308) is a (passing) test run of this branch vs NVDA.
[Here](https://github.com/gnarf/aria-at-gh-actions-helper/actions/runs/14781602901/job/41501542561#step:23:47) is a (failing) test run of this branch vs Voiceover
> update to userIntent versions for nvda workflow

- run-tester.ps1
@gnarf I'm especially interested in your thoughts on the removal of "Trace-Logs". That function combines distinct streams of logging information, and that makes it harder for me to understand the context of any given line of output. Additionally, because `run-tester.ps1` invokes the function twice (and the relevant logs are not cleared between invocations), a lot of information is duplicated in standard output.
> Improve logging

- stressor/stress-test.mts
This bug has been around for a while, but the consistency report has never been pushing the "browser" flag correctly to the workflow.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1210794475209283
> actually push browser flag to dispatch

- JAWS/InstallJAWSUnattended.ps1
These settings are not yet controllable via the at-driver, so we are setting up the config file before launching JAWS.
This is another "remove after we don't need it" patch for JAWS, but should result in more stable/comparable results.
> Setup some Jaws settings (temporary workaround)
